ifs=wlan0
port=80
model=IMX8MP-Dashcam
manufacturer=Omnidya
firmware_ver=1.0
serial_num=001
hardware_id=IMX8MP
scope=onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/Profile/G onvif://www.onvif.org/Profile/T onvif://www.onvif.org/Profile/M
ptz=0
adv_fault_if_unknown=0
adv_enable_media2=1

name=Profile_0
width=1280
height=720
url=rtsp://%s:554/stream
snapurl=http://%s/onvif/snapshot
type=H264

name=Profile_1
width=640
height=360
url=rtsp://%s:554/stream_inside
snapurl=http://%s/onvif/snapshot
type=H265
